sudo: required

services:
  - docker

language: python

addons:
  sonarcloud:
    organization: "abhinit06" # the key of the org you chose at step #3

script:
  - sonar-scanner
  - python -m pytest -v

after_success:
  - sh .travis/deploy_dockerhub.sh
  - test "$TRAVIS_BRANCH" = "master" && sh .travis/deploy_heroku.sh
